name: '[github-visits-badge] Actions when create new PR'

on:
  push:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies server
      run: | # run multiple commands
        npm ci
    - name: Run tests server
      run: npm run test
      env:
        APP_ENV: test
        POSTGRES_USER: ${{ secrets.POSTGRES_USER_TEST }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_TEST }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST_TEST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT_TEST }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB_TEST }}
        GITHUB_ID: ${{ secrets.GITHUB_ID_TEST }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TEST }}
        HTTP_PORT: 8080
